(function (app) {
  const roles = {
    Admin: "Admin",
    InventoryManager: "InventoryManager",
    StoreManager: "StoreManager",
    Cashier: "Cashier"
  };

  const allOpsRoles = [roles.Admin, roles.InventoryManager, roles.StoreManager];
  const storeRoles = [roles.Admin, roles.StoreManager];
  const sellRoles = [roles.Admin, roles.StoreManager, roles.Cashier];

  app.config = {
    appName: "RetailOps",
    storagePrefix: "retailops.web",
    taxRate: 0.05,
    roles,
    dataFiles: {
      products: "data/products.json",
      skus: "data/skus.json",
      inventory: "data/inventory.json",
      promotions: "data/promotions.json",
      replenishment: "data/replenishment.json",
      forecast: "data/forecast.json",
      suppliers: "data/suppliers.json",
      warehouses: "data/warehouses.json",
      activityLogs: "data/activityLogs.json",
      orders: "data/orders.json",
      users: "data/users.json",
      settings: "data/settings.json"
    },
    routes: [
      { id: "dashboard", path: "#/dashboard", title: "Dashboard", subtitle: "Executive inventory, replenishment, and promotion control tower.", icon: "D", section: "Workspace", roles: Object.values(roles) },
      { id: "products", path: "#/products", title: "Product Management", subtitle: "Maintain product catalog, pricing, thresholds, suppliers, and lifecycle state.", icon: "P", section: "Master Data", roles: allOpsRoles },
      { id: "skus", path: "#/skus", title: "SKU Management", subtitle: "Control SKU attributes, case packs, channels, barcodes, and sellable state.", icon: "S", section: "Master Data", roles: allOpsRoles },
      { id: "inventory", path: "#/inventory", title: "Inventory Overview", subtitle: "Warehouse stock, safety stock, and controlled stock movement workflows.", icon: "I", section: "Operations", roles: allOpsRoles },
      { id: "replenishment", path: "#/replenishment", title: "Replenishment Engine", subtitle: "Threshold-driven reorder recommendations with approval tracking.", icon: "R", section: "Operations", roles: allOpsRoles },
      { id: "promotions", path: "#/promotions", title: "Promo Engine", subtitle: "Promotion scopes, discount calculation, activity status, and eligibility tests.", icon: "%", section: "Commercial", roles: storeRoles },
      { id: "forecast", path: "#/forecast", title: "Forecasting", subtitle: "Demand forecast, cover days, seasonal lift, and stockout risk signals.", icon: "F", section: "Planning", roles: allOpsRoles },
      { id: "reports", path: "#/reports", title: "Reports", subtitle: "Sales, low-stock, promotion, and exportable planning reports.", icon: "B", section: "Planning", roles: allOpsRoles },
      { id: "billing", path: "#/billing", title: "Billing", subtitle: "POS-style order creation that applies the best promotion and deducts stock.", icon: "$", section: "Commercial", roles: sellRoles },
      { id: "settings", path: "#/settings", title: "Settings", subtitle: "Local simulation settings, data reset, and workspace controls.", icon: "G", section: "System", roles: [roles.Admin] },
      { id: "logs", path: "#/logs", title: "Logs / Activity", subtitle: "Audit trail generated by login, product, inventory, promo, and billing actions.", icon: "L", section: "System", roles: [roles.Admin] }
    ],
    promotionTypes: [
      { value: "Percentage", label: "Percentage" },
      { value: "FlatDiscount", label: "Flat Discount" },
      { value: "BuyOneGetOne", label: "Buy One Get One" },
      { value: "ComboOffer", label: "Combo Offer" }
    ]
  };
})(window.RetailOps = window.RetailOps || {});
